kind: pipeline
name: testing

steps:
- name: run flutter test
  pull: always
  image: appleboy/flutter-docker:1.2.1
  commands:
    - flutter channel stable
    - flutter upgrade
    - flutter packages pub get
    - flutter test test/*
